# These are supported funding model platforms

# GitHub Sponsors
github: # Add your GitHub Sponsors username here if you set it up

# Custom links (Stripe, Buy Me a Coffee, etc.)
custom: ['https://buy.stripe.com/bJe3cvdlxdy16fD7065wI00']
